name: Deploy model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python & install Cog
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Cog via pip
        run: pip install cogapp

      - name: Login to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          cog login $REPLICATE_API_TOKEN

      - name: Push model to Replicate
        run: |
          cog push r8.im/pintoldonovan6/pngbilasgenerator
