name: Deploy model to Replicate

on:
  push:
    branches:
      - main  # your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # Install jq to parse JSON
          sudo apt-get update && sudo apt-get install -y jq curl

      - name: Install Cog CLI
        run: |
          COG_VERSION=$(curl -s https://api.github.com/repos/replicate/cog/releases/latest | jq -r '.tag_name')
          echo "Installing Cog CLI version $COG_VERSION"
          curl -fsSL https://github.com/replicate/cog/releases/download/${COG_VERSION}/cog-linux-amd64 -o cog
          chmod +x cog
          sudo mv cog /usr/local/bin/cog
          cog --version

      - name: Login to Replicate
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          cog login --token $API_TOKEN

      - name: Push model to Replicate
        run: |
          cog push r8.im/pintoldonovan6/pngbilasgenerator
