name: Deploy model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Cog
        run: pip install cogapp

      - name: Login to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python -m cogapp login --token $REPLICATE_API_TOKEN

      - name: Push model to Replicate
        run: python -m cogapp push r8.im/pintoldonovan6/png-pattern-ai-image-generator
