name: Deploy model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cog CLI
        run: |
          curl -fsSL https://github.com/replicate/cog/releases/download/v0.9.1/cog-linux-amd64 -o cog
          chmod +x cog
          sudo mv cog /usr/local/bin/cog

      - name: Push model to Replicate
        env:
          COG_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: cog push r8.im/pintoldonovan6/pngbilasgenerator
