name: Deploy model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Cog
        run: pip install cog

      - name: Push model to Replicate
        env:
          COG_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: cog push r8.im/pintoldonovan6/pngbilasgenerator
